/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Colaborador;

import Usuario.Cliente;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author ACER15
 */
public class InterfaceAreaTrabajo_Colaborador extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceAreaTrabajo_Colaborador
     */
    String rutaClientes ="C:\\Users\\ACER15\\Desktop\\Progra 1\\programas\\Proyecto 2\\Archivos de texto\\Clientes.txt";
    public InterfaceAreaTrabajo_Colaborador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
//    public int insertarEstudiante(Cliente cliente)
//    {
//    
//        
//        File file = new File(ruta);       
//        int insertado = 0;
//        
//        System.out.println("Creamos un FIleWriter");
//        FileWriter flWriter = null;
//        try 
//        {
//            //crear el archivo en disco duro, 
//            if(!file.exists())
//                file.createNewFile();
//            
//            //recibe como parametro un empleadoCajero
//            System.out.println("Inicializamos el flWriter");
//            flWriter = new FileWriter(file.getAbsoluteFile(),true);
//            
//            System.out.println("Creamos un BufferedWriter");
//            BufferedWriter brWriter = new BufferedWriter(flWriter);
//     
//            if(!buscarEstudiante(estudiante.getNombre()))
//            {
//                brWriter.write(
//
//                       estudiante.getCarne()+","+
//                       estudiante.getNombre()+","+
//                       estudiante.getNota()
//                      );
//                brWriter.newLine();
//                insertado = 1;
//            }
//            
//            System.out.println("Cerramos conexion");
//            brWriter.close();
//        } catch (IOException e) 
//        {
//            System.out.println("Error");
//            e.printStackTrace();
//        } finally
//        {
//            if(flWriter != null)
//            {
//                try 
//                {
//                    flWriter.close();
//                } catch (IOException e) 
//                {
//                    e.printStackTrace();
//                }
//            }
//            
//        }
//        
//        return insertado;
//        
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
